// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-aWna96Q7P8qYWrg_HjyShhP_DA5vREA',
    appId: '1:3192605048:web:0bf7520ed8694a7da1608d',
    messagingSenderId: '3192605048',
    projectId: 'toko-online-a487d',
    authDomain: 'toko-online-a487d.firebaseapp.com',
    storageBucket: 'toko-online-a487d.firebasestorage.app',
    measurementId: 'G-B29T4LDGJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgRx_TbssEk_VZyrOLQesIuWPvKnfYEcI',
    appId: '1:3192605048:android:a24dd600ef616774a1608d',
    messagingSenderId: '3192605048',
    projectId: 'toko-online-a487d',
    storageBucket: 'toko-online-a487d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc79OSJIfUlo3UPkm0_pNiCQ4eOIinK8Y',
    appId: '1:3192605048:ios:954a5d693b7f56f4a1608d',
    messagingSenderId: '3192605048',
    projectId: 'toko-online-a487d',
    storageBucket: 'toko-online-a487d.firebasestorage.app',
    iosBundleId: 'com.example.tokoonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc79OSJIfUlo3UPkm0_pNiCQ4eOIinK8Y',
    appId: '1:3192605048:ios:954a5d693b7f56f4a1608d',
    messagingSenderId: '3192605048',
    projectId: 'toko-online-a487d',
    storageBucket: 'toko-online-a487d.firebasestorage.app',
    iosBundleId: 'com.example.tokoonline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-aWna96Q7P8qYWrg_HjyShhP_DA5vREA',
    appId: '1:3192605048:web:23b5348919642981a1608d',
    messagingSenderId: '3192605048',
    projectId: 'toko-online-a487d',
    authDomain: 'toko-online-a487d.firebaseapp.com',
    storageBucket: 'toko-online-a487d.firebasestorage.app',
    measurementId: 'G-D3SFQ9Z46T',
  );

}